name: ZWADMIN
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
    build_and_relase:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2.1.4

        - name: Build source
          run: |
            npm install
            npm run build:prod

        - name: tar package
          uses: montudor/action-zip@v0.1.1
          with:
            args: zip -q -r ZWADMIN.zip . -i ./dist/zhiweiAdmin/*

        - name: tansfer and release
          uses: wlixcc/SFTP-Deploy-Action@v1.0
          with:
            username: ${{secrets.HOST_USER}}
            server: ${{ secrets.HOST }}
            ssh_private_key: ${{ secrets.TENCENT_HOST_PRIVATE_KEY }}
            local_path: ZWADMIN.zip
            remote_path: '/home/zwAdmin/'

    clear_old_file:
      needs: [build_and_relase]
      name: clear and renew
      runs-on: ubuntu-latest
      steps:
        - name: clear the file and unzip
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.HOST_USER }}
            key: ${{ secrets.TENCENT_HOST_PRIVATE_KEY }}
            script: |
              rm -r /home/zwAdmin/prod
              unzip -qq -j /home/zwAdmin/ZWADMIN.zip -d /home/zwAdmin/prod
              rm -r /home/zwAdmin/ZWADMIN.zip
